spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mbti_music
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 5000
