spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mbti_music
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

mybatis:
  type-aliases-package: com.mkkang.mbti_with_music.domain
  mappper-locations: mappers/*.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500

server:
  port: 5000
